apiVersion: v1
kind: Secret
metadata:
  name: pacman-secret
  namespace: grupo2
  labels:
    app: grupo2
type: Opaque
data:
  MONGO_SERVICE_HOST: bW9uZ28=  #mongo
  MONGO_AUTH_USER: YXBwX3VzZXI=  #app_user
  MONGO_AUTH_PWD: YXBwX3Bhc3M= #app_pass
  MONGODB_DATABASE: cGFjbWFu #pacman


   