apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: grupo2
  labels:
    app: grupo2
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA== #root
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0 #secret
  MONGODB_USER: YXBwX3VzZXI= #app_user
  MONGODB_PASSWORD: YXBwX3Bhc3M= #app_pass
stringData:
  MONGODB_DATABASE: "pacman"